### ISSUE TITLE
Dont wrap schema

### ISSUE THREAD

**Issue by psi-4ward** [kulakowka/feathers-validate-hook#2]
Hi,

why do you [wrap given Schema](https://github.com/kulakowka/feathers-validate-hook/blob/master/lib/validate/index.js#L8) ?

So i can not add additional Schema stuff like `additionalProperties`, `definitions` or even `patternProperties`.

Perhaps we could only wrap it if the source-schema Obj does not include a `properties` prop?

**Comment by sean-nicholas** [comment]
Thought the same. But I would remove https://github.com/kulakowka/feathers-validate-hook/blob/master/lib/validate/index.js#L8-L12
The developer should be responsible for providing the correct schema. 

@kulakowka What do you think? I could create a pr if you want

**Comment by kulakowka** [comment]
@sean-nicholas I'll be very happy;

**Comment by sean-nicholas** [comment]
@kulakowka Oh, I see you fixed it already :smile: So I think we can close this issue.
